### ISSUE TITLE
Login buttons

### ISSUE THREAD

**Issue by erinzm** [MayOneUS/teams#10]
The login modal idea was discarded - but it seems that the buttons reverted to the old, plain kind.
Anyone want me to attach the styles to the buttons? - Bootstrap and my library `share.css` are both loaded, so it should be a snap.

**Comment by jtolio** [comment]
the login modal also exists i think? there's just two pages where all we have to show is login options. 

it would be awesome if the styles matched imo

**Comment by aaronlifshin** [comment]
The whole login situation is kind of a mess right now.

A

**Comment by erinzm** [comment]
Is the auth handler still working? I _thought_ I heard it was broken.

**Comment by aaronlifshin** [comment]
Working fine for me.  Stressful type of email to receive.

**Comment by jtolio** [comment]
when did you hear it was broken?

**Comment by erinzm** [comment]
Going to take care of this in a PR next week.
Closed.

**Comment by erinzm** [comment]
Oh man. It looks like there's the _main_ blue buttons on that page, and then hitting **login** brings up the modal. We need to remove one of them, comments @aaronlifshin?
Who else is managing this now?

**Comment by aaronlifshin** [comment]
Yes. This all became a total mess.

Right now the login link on the main site just takes people over to that
page.

I think the simplest might be to just get rid of the modal?

A

**Comment by erinzm** [comment]
I can do that. Do you want PRs or direct pushes?

**Comment by aaronlifshin** [comment]
Direct push is fine if you are 100% confident.  If you want a review, then
PR.

A

**Comment by erinzm** [comment]
I'm 100%, but you'll still need to redeploy the repo to GAE.
Can I get push access? Don't mean to bother you...

**Comment by aaronlifshin** [comment]
Yes, I will redeploy after.  You should have push access, I think.

**Comment by erinzm** [comment]
Can't tell if I do, would I be listed as `Collaborator` then?
I don't think I ever got added either.

**Comment by erinzm** [comment]
It works now, @aaronlifshin can you do a GAE deploy?

**Comment by erinzm** [comment]
BTW I added FontAwesome back in, it's from a different CDN, any trouble with that @aaronlifshin &c?

**Comment by aaronlifshin** [comment]
Could have sworn I had added you, but just added you again.

**Comment by erinzm** [comment]
@aaronlifshin Added me to what?

**Comment by aaronlifshin** [comment]
Commuters list for Mayone us

**Comment by erinzm** [comment]
Ah, I'm on the list. Can you do a GAE push though?

**Comment by aaronlifshin** [comment]
Heard you. When I have a chance, I will push. Tonight or possibly tomorrow.

**Comment by erinzm** [comment]
Thanks. Can we have Travis push to GAE on master when builds pass, or are
you or Lessig opposed to that?

**Comment by brad** [comment]
Teams doesn't have a test suite or Travis configuration yet.

**Comment by erinzm** [comment]
Heh. Gonna close this, @aaronlifshin's pushing this tonight.

**Comment by erinzm** [comment]
Pushed to GAE.

**Comment by aaronlifshin** [comment]
I believe this change broke the login link on the pledge (team) pages
itself.

Can you check if you are able to log in from a team page?

A

**Comment by brad** [comment]
When I click "Login" on a team page, nothing happens.

**Comment by erinzm** [comment]
Ah, you mean the modal?

**Comment by erinzm** [comment]
I'll put that code back.

**Comment by brad** [comment]
Yeah, that button definitely expects a modal present:

``` html
<button data-toggle="modal" data-target="#login_modal">Login</button>
```

**Comment by aaronlifshin** [comment]
We just need it to go over the to the /Login page, I guess.

A

**Comment by erinzm** [comment]
I just put the modal back, you can take it from there.
