### ISSUE TITLE
https glitch on creative commons image

### ISSUE THREAD

**Issue by jwhite66** [MayOneUS/teams#11]
I get the scary yellow arrow in Chrome for this link:
  http://i.creativecommons.org/l/by/4.0/80x15.png

**Comment by brad** [comment]
That should fix it once it's deployed.

**Comment by aaronlifshin** [comment]
Should be deployed.  Can you please check and close?

A

**Comment by jwhite66** [comment]
Yes, this issue is closed.  The video causes the next one :-(.  I'll open a separate issue.
