### ISSUE TITLE
Team page queries pledge.mayday.us/total, not pledge.mayday.us/r/total

### ISSUE THREAD

**Issue by hjfreyer** [MayOneUS/teams#13]
The latter is actually tested and returns all the info the team page needs, so we don't need to do two RPCs.

**Comment by piebob** [comment]
yeah, my team page progress bar is showing almost $100K less than the main page.

**Comment by aaronlifshin** [comment]
I fixed both handlers to reflect the new total.

**Comment by brad** [comment]
This was done in d159dc4c6fd725c9ab11b850342e9932d759a9d7
