### ISSUE TITLE
Small UI/stylistic issue

### ISSUE THREAD

**Issue by erinzm** [MayOneUS/teams#2]
When on `my.mayone.us`, it's not evident (for most users) how to get _back_ to `mayone.us`.

**Comment by nelsonpecora** [comment]
:+1: that's a good point

**Comment by aaronlifshin** [comment]
Hmm... we could just roll with the same logo form root homepage, and have
that go back?
A

**Comment by erinzm** [comment]
Fixed, thanks ;)
It was really bugging me.
